# Generated by Django 5.2 on 2025-04-25 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('cnh', models.CharField(max_length=20, unique=True)),
                ('data_validade_cnh', models.DateField()),
                ('endereco', models.TextField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motoristas', to='veiculos.veiculo')),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['slug'], name='motoristas__slug_885285_idx'), models.Index(fields=['cpf'], name='motoristas__cpf_967bef_idx')],
            },
        ),
    ]
