# Generated by Django 5.2 on 2025-04-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoristas', '0001_initial'),
        ('veiculos', '0002_alter_veiculo_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='motorista',
            name='motoristas__slug_885285_idx',
        ),
        migrations.RenameField(
            model_name='motorista',
            old_name='data_cadastro',
            new_name='data_criacao',
        ),
        migrations.AddField(
            model_name='motorista',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='endereco',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='motorista',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='telefone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='motorista',
            index=models.Index(fields=['cnh'], name='motoristas__cnh_5b4662_idx'),
        ),
        migrations.AddIndex(
            model_name='motorista',
            index=models.Index(fields=['data_validade_cnh'], name='motoristas__data_va_4be5f7_idx'),
        ),
    ]
