# Generated by Django 5.2 on 2025-04-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0004_alter_endereco_cidade_alter_endereco_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
