# Generated by Django 5.2 on 2025-04-28 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_alter_cliente_options_cliente_data_atualizacao_and_more'),
        ('vendas', '0002_remove_venda_total_venda_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['status'], name='vendas_vend_status_be1af5_idx'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['data_venda'], name='vendas_vend_data_ve_933af3_idx'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['cliente'], name='vendas_vend_cliente_0d3155_idx'),
        ),
        migrations.AddConstraint(
            model_name='venda',
            constraint=models.CheckConstraint(condition=models.Q(('valor_total__gte', 0)), name='venda_valor_total_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='venda',
            constraint=models.CheckConstraint(condition=models.Q(('desconto__gte', 0)), name='venda_desconto_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='venda',
            constraint=models.CheckConstraint(condition=models.Q(('valor_final__gte', 0)), name='venda_valor_final_nao_negativo'),
        ),
    ]
