# Generated by Django 5.2 on 2025-04-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veiculo',
            options={'ordering': ['placa'], 'verbose_name': 'Veículo', 'verbose_name_plural': 'Veículos'},
        ),
        migrations.RemoveIndex(
            model_name='veiculo',
            name='veiculos_ve_slug_ee61ff_idx',
        ),
        migrations.RenameField(
            model_name='veiculo',
            old_name='data_cadastro',
            new_name='data_criacao',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='cor',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='marca',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name='veiculo',
            index=models.Index(fields=['chassi'], name='veiculos_ve_chassi_8d1c2b_idx'),
        ),
        migrations.AddIndex(
            model_name='veiculo',
            index=models.Index(fields=['renavam'], name='veiculos_ve_renavam_95cc9a_idx'),
        ),
    ]
