# Generated by Django 5.2 on 2025-04-25 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itens_venda', '0001_initial'),
        ('pedidos', '0001_initial'),
        ('produtos', '0004_remove_produto_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_venda', to='pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_venda', to='produtos.produto'),
        ),
    ]
