# Generated by Django 5.2 on 2025-04-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationcontext',
            options={'ordering': ['-last_interaction']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='conversationcontext',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationcontext',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conversationcontext',
            name='last_interaction',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='conversationcontext',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_handled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='message',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='conversationcontext',
            index=models.Index(fields=['session_id'], name='chatbot_con_session_402414_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationcontext',
            index=models.Index(fields=['last_interaction'], name='chatbot_con_last_in_1eed23_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationcontext',
            index=models.Index(fields=['is_active'], name='chatbot_con_is_acti_0511ff_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['session_id'], name='chatbot_mes_session_39eef8_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['timestamp'], name='chatbot_mes_timesta_59b6f7_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['intent'], name='chatbot_mes_intent_75b83f_idx'),
        ),
    ]
