# Generated by Django 5.2 on 2025-04-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cidade_estado_alter_endereco_cidade_cidade_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
