# Generated by Django 5.2 on 2025-04-28 01:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa',
            name='data_abertura',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caixa',
            name='data_fechamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caixa',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado')], default='aberto', max_length=20),
        ),
        migrations.AddField(
            model_name='movimentacaofinanceira',
            name='caixa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='financeiro.caixa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimentacaofinanceira',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='movimentacaofinanceira',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcela',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcela',
            name='juros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='parcela',
            name='multa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='parcela',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planodecontas',
            name='categoria',
            field=models.CharField(choices=[('produto', 'Produto'), ('servico', 'Serviço'), ('comissao', 'Comissão'), ('outros', 'Outros')], default='outros', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planodecontas',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], default='entrada', max_length=10),
            preserve_default=False,
        ),
    ]
