# Generated by Django 5.2 on 2025-04-24 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_estoque_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoque',
            options={},
        ),
    ]
