# Generated by Django 5.2 on 2025-04-28 03:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_alter_estoque_options'),
        ('produtos', '0004_remove_produto_estoque'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='estoque',
            index=models.Index(fields=['produto'], name='estoque_est_produto_bf0b51_idx'),
        ),
        migrations.AddIndex(
            model_name='estoque',
            index=models.Index(fields=['quantidade'], name='estoque_est_quantid_d59f46_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentoestoque',
            index=models.Index(fields=['produto'], name='estoque_mov_produto_a2537b_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentoestoque',
            index=models.Index(fields=['data'], name='estoque_mov_data_9c486e_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentoestoque',
            index=models.Index(fields=['tipo'], name='estoque_mov_tipo_4a4769_idx'),
        ),
        migrations.AddConstraint(
            model_name='estoque',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gte', 0)), name='estoque_quantidade_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='estoque',
            constraint=models.CheckConstraint(condition=models.Q(('custo_medio__gte', 0)), name='estoque_custo_medio_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='movimentoestoque',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='movimento_quantidade_positiva'),
        ),
        migrations.AddConstraint(
            model_name='movimentoestoque',
            constraint=models.CheckConstraint(condition=models.Q(('custo_unitario__gte', 0)), name='movimento_custo_unitario_nao_negativo'),
        ),
    ]
