# Generated by Django 5.0.6 on 2024-07-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_myuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='force_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
