# Generated by Django 5.2 on 2025-04-17 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque', models.IntegerField(default=0)),
                ('estoque_minimo', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('indisponivel', 'Indisponível'), ('promocao', 'Promoção')], default='disponivel', max_length=20)),
                ('status_message', models.CharField(blank=True, max_length=255, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('promocao_inicio', models.DateTimeField(blank=True, null=True)),
                ('promocao_fim', models.DateTimeField(blank=True, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'indexes': [models.Index(fields=['slug'], name='produtos_pr_slug_e58355_idx'), models.Index(fields=['categoria'], name='produtos_pr_categor_b0e6ca_idx')],
            },
        ),
    ]
