# Generated by Django 5.2 on 2025-04-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='altura',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Altura do produto em centímetros.', max_digits=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='largura',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Largura do produto em centímetros.', max_digits=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='peso',
            field=models.PositiveIntegerField(default=0, help_text='Peso do produto em gramas.'),
        ),
        migrations.AddField(
            model_name='produto',
            name='profundidade',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Profundidade do produto em centímetros.', max_digits=10),
        ),
    ]
