# Generated by Django 5.2 on 2025-04-24 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_altura_produto_largura_produto_marca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='estoque',
        ),
    ]
