# Generated by Django 5.2 on 2025-04-25 14:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedores', '0002_alter_fornecedor_options_fornecedor_cnpj_and_more'),
        ('produtos', '0004_remove_produto_estoque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('custo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_compra', models.DateTimeField(default=django.utils.timezone.now)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='fornecedores.fornecedor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='produtos.produto')),
            ],
        ),
    ]
