# Generated by Django 5.2 on 2025-04-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_compra_valor_final_alter_compra_valor_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
