# Generated by Django 5.2 on 2025-04-28 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_compra_slug'),
        ('fornecedores', '0003_alter_fornecedor_options_and_more'),
        ('produtos', '0004_remove_produto_estoque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnh', models.CharField(max_length=20, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('ano', models.PositiveIntegerField()),
                ('cor', models.CharField(max_length=30)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='data_chegada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='data_emissao_nf',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='data_saida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='numero_nota_fiscal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='serie_nota_fiscal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='motorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='compras.motorista'),
        ),
        migrations.AddField(
            model_name='compra',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='compras.veiculo'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['numero_nota_fiscal'], name='compras_com_numero__1aa73e_idx'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['motorista'], name='compras_com_motoris_7286ce_idx'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['veiculo'], name='compras_com_veiculo_947368_idx'),
        ),
    ]
