# Generated by Django 5.2 on 2025-04-28 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_motorista_veiculo_compra_data_chegada_and_more'),
        ('motoristas', '0002_remove_motorista_motoristas__slug_885285_idx_and_more'),
        ('veiculos', '0002_alter_veiculo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='motorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='motoristas.motorista'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='veiculos.veiculo'),
        ),
    ]
