# Generated by Django 5.2 on 2025-04-28 01:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servico',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='servico',
            name='forma_pagamento',
            field=models.CharField(choices=[('avista', 'À Vista'), ('prazo', 'A Prazo'), ('boleto', 'Boleto'), ('cartao', 'Cartão de Crédito')], default='avista', max_length=20),
        ),
        migrations.AddField(
            model_name='servico',
            name='numero_parcelas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='servico',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='valor_final',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
