# Generated by Django 5.2 on 2025-04-08 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_comment_options_remove_comment_author_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
