# Generated by Django 5.2 on 2025-04-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0002_alter_fornecedor_options_fornecedor_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'ordering': ['-data_cadastro'], 'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='condicao_pagamento',
            field=models.CharField(choices=[('a_vista', 'À Vista'), ('30_dias', '30 Dias'), ('60_dias', '60 Dias'), ('90_dias', '90 Dias'), ('personalizado', 'Personalizado')], default='30_dias', max_length=50),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='limite_credito',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='prazo_pagamento',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='saldo_devedor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('bloqueado', 'Bloqueado'), ('pre_cadastro', 'Pré-cadastro')], default='pre_cadastro', max_length=20),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='total_compras',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='total_servicos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='ultima_compra',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
